---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install basic packages
  apt:
    name:
      - curl
      - wget
      - git
      - htop
      - vim
      - ufw
    state: present

- name: Setup timezone
  timezone:
    name: UTC

- name: Create construct user
  user:
    name: construct
    system: yes
    shell: /bin/bash

- name: Create directories
  file:
    path: /opt/construct
    state: directory
    owner: construct
    group: construct
    mode: '0755'

- name: Setup firewall
  ufw:
    rule: allow
    port: "22"
    proto: tcp
