[package]
name = "construct-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.21"
tokio-rustls = "0.24"
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono"] }
redis = { version = "0.24", features = ["tokio-comp", "connection-manager", "tokio-rustls-comp"] }
uuid = { version = "1", features = ["v4", "serde"] }
bcrypt = "0.15"
anyhow = "1"
dotenvy = "0.15"
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Crypto
x25519-dalek = { version = "2.0", features = ["static_secrets"] }
chacha20poly1305 = "0.10"
ed25519-dalek = "2"
rand = "0.8"
hyper = { version = "1.8.1", features = ["http1", "server"] }
prometheus = "0.14.0"
once_cell = "1.21.3"
hyper-util = { version = "0.1.19", features = ["tokio"] }
http-body-util = "0.1.3"
bytes = "1.11.0"
rmp-serde = "1.3.0"
