---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Copy nginx config
  copy:
    src: ../../../nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: reload nginx

- name: Copy SSL certificates
  copy:
    src: ../../../security/ssl/
    dest: /etc/ssl/certs/
  when: ssl_certs_exist

- handlers:
  - name: reload nginx
    service:
      name: nginx
      state: reloaded
